// Role-based permissions
export const ROLES = {
  SUPER_ADMIN: "SUPER_ADMIN",
  ADMIN_EMPRESA: "ADMIN_EMPRESA",
  CONTABILIDAD: "CONTABILIDAD",
  TESORERIA: "TESORERIA",
  GERENCIA: "GERENCIA",
  AUDITOR: "AUDITOR",
} as const;

export type RoleName = (typeof ROLES)[keyof typeof ROLES];

// Module permissions
export const PERMISSIONS = {
  // Dashboard
  DASHBOARD_VIEW: [ROLES.SUPER_ADMIN, ROLES.ADMIN_EMPRESA, ROLES.CONTABILIDAD, ROLES.TESORERIA, ROLES.GERENCIA, ROLES.AUDITOR],

  // Vouchers (Compras/Ventas)
  VOUCHER_VIEW: [ROLES.SUPER_ADMIN, ROLES.ADMIN_EMPRESA, ROLES.CONTABILIDAD, ROLES.TESORERIA, ROLES.GERENCIA, ROLES.AUDITOR],
  VOUCHER_CREATE: [ROLES.SUPER_ADMIN, ROLES.ADMIN_EMPRESA, ROLES.CONTABILIDAD],
  VOUCHER_UPDATE: [ROLES.SUPER_ADMIN, ROLES.ADMIN_EMPRESA, ROLES.CONTABILIDAD],
  VOUCHER_DELETE: [ROLES.SUPER_ADMIN, ROLES.ADMIN_EMPRESA],
  VOUCHER_VALIDATE: [ROLES.SUPER_ADMIN, ROLES.ADMIN_EMPRESA, ROLES.CONTABILIDAD],
  VOUCHER_APPROVE: [ROLES.SUPER_ADMIN, ROLES.ADMIN_EMPRESA, ROLES.GERENCIA],

  // Detracciones
  DETRACTION_VIEW: [ROLES.SUPER_ADMIN, ROLES.ADMIN_EMPRESA, ROLES.CONTABILIDAD, ROLES.TESORERIA, ROLES.GERENCIA, ROLES.AUDITOR],
  DETRACTION_PAY: [ROLES.SUPER_ADMIN, ROLES.ADMIN_EMPRESA, ROLES.TESORERIA],

  // Documentos
  DOCUMENT_VIEW: [ROLES.SUPER_ADMIN, ROLES.ADMIN_EMPRESA, ROLES.CONTABILIDAD, ROLES.TESORERIA, ROLES.GERENCIA, ROLES.AUDITOR],
  DOCUMENT_DOWNLOAD: [ROLES.SUPER_ADMIN, ROLES.ADMIN_EMPRESA, ROLES.CONTABILIDAD, ROLES.TESORERIA, ROLES.GERENCIA],

  // Alertas
  ALERT_VIEW: [ROLES.SUPER_ADMIN, ROLES.ADMIN_EMPRESA, ROLES.CONTABILIDAD, ROLES.TESORERIA, ROLES.GERENCIA, ROLES.AUDITOR],
  ALERT_MANAGE: [ROLES.SUPER_ADMIN, ROLES.ADMIN_EMPRESA],

  // Cuentas
  ACCOUNT_VIEW: [ROLES.SUPER_ADMIN, ROLES.ADMIN_EMPRESA, ROLES.CONTABILIDAD, ROLES.TESORERIA, ROLES.GERENCIA, ROLES.AUDITOR],
  ACCOUNT_MANAGE: [ROLES.SUPER_ADMIN, ROLES.ADMIN_EMPRESA, ROLES.TESORERIA],

  // Reportes
  REPORT_VIEW: [ROLES.SUPER_ADMIN, ROLES.ADMIN_EMPRESA, ROLES.CONTABILIDAD, ROLES.TESORERIA, ROLES.GERENCIA, ROLES.AUDITOR],
  REPORT_GENERATE: [ROLES.SUPER_ADMIN, ROLES.ADMIN_EMPRESA, ROLES.CONTABILIDAD, ROLES.GERENCIA],

  // Descargas SUNAT
  DOWNLOAD_VIEW: [ROLES.SUPER_ADMIN, ROLES.ADMIN_EMPRESA, ROLES.CONTABILIDAD],
  DOWNLOAD_EXECUTE: [ROLES.SUPER_ADMIN, ROLES.ADMIN_EMPRESA, ROLES.CONTABILIDAD],

  // Company
  COMPANY_VIEW: [ROLES.SUPER_ADMIN, ROLES.ADMIN_EMPRESA, ROLES.GERENCIA],
  COMPANY_UPDATE: [ROLES.SUPER_ADMIN, ROLES.ADMIN_EMPRESA],

  // Users
  USER_VIEW: [ROLES.SUPER_ADMIN, ROLES.ADMIN_EMPRESA],
  USER_MANAGE: [ROLES.SUPER_ADMIN, ROLES.ADMIN_EMPRESA],
} as const;

export function hasPermission(userRoles: string[], permission: keyof typeof PERMISSIONS): boolean {
  const allowedRoles = PERMISSIONS[permission] as readonly string[];
  return userRoles.some((role) => allowedRoles.includes(role));
}

export function canAccessModule(userRoles: string[], module: string): boolean {
  const modulePermissions: Record<string, keyof typeof PERMISSIONS> = {
    dashboard: "DASHBOARD_VIEW",
    compras: "VOUCHER_VIEW",
    ventas: "VOUCHER_VIEW",
    detracciones: "DETRACTION_VIEW",
    documentos: "DOCUMENT_VIEW",
    alertas: "ALERT_VIEW",
    "cuentas-cobrar": "ACCOUNT_VIEW",
    "cuentas-pagar": "ACCOUNT_VIEW",
    reportes: "REPORT_VIEW",
    ia: "DASHBOARD_VIEW",
  };

  const permission = modulePermissions[module];
  return permission ? hasPermission(userRoles, permission) : false;
}
